"$schema" = 'https://starship.rs/config-schema.json'



format = """
$directory\
$python\
$line_break\
$character\
"""
[character]
success_symbol = "[\\$](bold blue) [>](bold purple)"

[hostname]
ssh_only = true 
format = "<[$hostname]($style)>"
trim_at = "@"
style = "bold dimmed white"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = false


[custom.tun0_address]
command = "~/bin/tun0-address.sh"
when = "ip addr show tun0"
symbol = ""
style = "bold bright-blue"
format = "\\[[$symbol]($style) [$output]($style)\\] "

[directory]
home_symbol="~"
format='[$path]($style) '
truncation_length=0
truncate_to_repo = false
style = "bold cyan"
use_logical_path = true
